---
  - name: Add Oracle java repository
    sudo: true
    apt_repository: repo="ppa:webupd8team/java"

  - name: Accept Java licence
    shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
    sudo: true
    args:
      creates: /etc/oracle-java-8-licence-acceptance

  - name: Install Oracle Java 8
    apt:
      name: "{{item}}"
      state: latest
    sudo: true
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default