---
- hosts: betonleague_hosts
  roles:
    - java
    - psql
    - deploy-play
  tasks:


#    - name: Package required for installing java
#      apt: pkg=python-software-properties state=installed update_cache=true
#
#      copy: src=../backend/betonplay/target/universal/betonplay-1.0-SNAPSHOT.zip dest=~
#    - name: Unzip copyed file